#!/usr/bin/env bash

if [ $# -ne  1 ]
then
    echo -e "Marathon launch script\n"
    echo -e "Usage: $0 [path_to_json_job_request]\n"
    echo -e "To launch webskeleton project: $0 webskel-task.json\n"
    exit 1
fi

json_job=$1

curl -H "content-type: application/json" -X POST -d @${json_job} http://172.31.0.100:8080/v2/apps/
